package org.firstinspires.ftc.teamcode.Resources;

@SuppressWarnings("ALL")
public enum Stone {
    DRIVE_STONE,
    STRAFESTONE1,
    STRAFESTONE2,
    STRAFESTONE3,
    FINDSTONE,
    DRIVETOSTONE,
    GETSTONE,
    DRIVE_BACK1,
    TURN901,
    DRIVE_BRIDGE,
    DROPSTONE,
    DRIVEBACKSTONE2,
    TURN_BACK90,
    STRAFE_STONE2,
    DRIVETOSTONE2,
    GETSTONE2,
    DRIVE_BACK2,
    TURN903,
    DRIVE_BRIDGE2,
    DROPSTONE2,
    DRIVEBRIDGE,
    STOP,

}